
spring:
  datasource: 
    url: jdbc:mysql://barra-app-brasil:3306/barra_app1.4?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: risq1942
   
